# Backend
bucket: "valis-develop"
region: "ap-northeast-1"
encrypt: true
key_prefix: "terraform/iam"

# IAM
iam_users:
  - "test_user1"
  - "test_user2"
iam_group_name: "test_group"
iam_group_membership_name: "iam_group_membership_name"
pgp_key: "mI0EYHP3KwEEANFqBv+dEyemtYcCgXIjcZtyawpIg4mK8TZixDzkfisZU0+/BVOXLWtRd6KphZQFrjitnRKOh3t2fQwpfVULb1M4nXrSvvtF6y/ehweV/QZ9FELRTB6HYNDRyyUGsipgrgaLqqDMyiYvSQpFm5LPrI/haBqHy8rQqP0URVuuz90fABEBAAG0BXZhbGlziLkEEwECACMFAmBz9ysCGwMHCwkIBwMCAQYVCAIJCgsEFgIDAQIeAQIXgAAKCRAQLjZDt9SRQoOzA/9JQXCVbbmZtBmfdFWho9im0d2KsRGRFvNzvfvbwbPeQHG4OpGkE1NGxIMy6PWrDP6WQkXm2uuUPVH7+NZPj0KZzq47c0ht2LMDmRZxw2Tz2lU9tfVxCeARw920vWTUSFnzgrNLtT3tTtkEDHC6dQ+egreJXq9DQxYUHdTcjizasbiNBGBz9ysBBAC3wVMD+VaKEJUrmqY2PRa5ObH/Vx3ottFTTcpketo2cbsrtZ/Pi6xcO85fb9a+HHCiCftFJM0033CObLxa/iyMjZoRVw2aqN8RcTJ4gPqN+QbzYzPKwNcdXz6VNV8uyoVdWi16vh1/jAqZrItH0L3oyRFA6sbDN55X6MJcR2Vk5wARAQABiJ8EGAECAAkFAmBz9ysCGwwACgkQEC42Q7fUkUIz3QQAocQiK2ZbRUgBG372py+mTFNRauBQF6v2tVv3gBSbwqi+sWv4VlJUKEMWHdmTzCQr8aJHVaVrSPhEM258rw6pBstqItcXeqnYHH+WCARPXhHZGGtGP89/YWqsAnp6tgZyJxvAreoZXqg5wM3SyXVAXHq/YP0R61h0VGa2tVuQP/k="