# Backend
bucket: "valis-develop"
region: "ap-northeast-1"
encrypt: true
key_prefix: "terraform/iam"

# IAM
iam_users:
  - "test_user1"
  - "test_user2"
iam_group_name: "test_group"
iam_group_membership_name: "iam_group_membership_name"
pgp_key: "mI0EYHPR/wEEALRo/haxPYeLAYZXgw3lbys0Yk45kpV4TG/adJzG6EC0ybvgrT2xlKm3FSvWV+FUEz6OXVN4irqzPk+2wMKajdVxYTh1rMB0TOrA1CGz6maWcJrBSqWbjruKsokEObp5D6SndAxGwJKbDKzT49inF1cr3WmXeWlTATu/YPrng94tABEBAAG0BXZhbGlziLkEEwECACMFAmBz0f8CGwMHCwkIBwMCAQYVCAIJCgsEFgIDAQIeAQIXgAAKCRAuNlFfwP8DRAq3A/kBoO0d5IfoCpbx10D1s0C7gNyoY3kjTs9zwn0oVrEbWDqj5MEna4wTpjxPpdHyr6PCC1GAuOz32NCdcZA7LG8WgnBqb2iHu4WaOgB28N+6hyl/GBu12hGaGctuyak7Tk4vewM4jVY/AA9pEoilUgZ7Nmjxy+QHuy4fGv7LTkh+ObiNBGBz0f8BBACm3AWQXSLnT7alET6DolkJZ9ZqgI9v/8bC6FAzsehCojP2jbJ2wev7eglUbU3Hy96K+dmM3w1XIpZC+2ZdUwdW68RWiKdnwYFTO+Lg1YySmRxRvWRo6Hc/QvYk6LPauB0BvEusATtyW/g60SitvlPVjSCVzxYKvM+cu/kcn5mE7wARAQABiJ8EGAECAAkFAmBz0f8CGwwACgkQLjZRX8D/A0ToXwP+NwguKNdmO6qBQF4oF1UonrX50NEShGFqNT5IdNOOTZBjw1AAGmXzyiED8/EeA329Q2ImI5NOPgEDD1U2GMRE6+NAccvKGPEH+ajO9xZP1vUE/F3WQvajRQp+jJ3uxH2JI4b0c3q9h4dIWJ+Mn4j+QwdjIm+o1ZmjAP4XUIWzK5o="