# Backend
bucket: "valis-develop"
region: "ap-northeast-1"
encrypt: true
key_prefix: "terraform/iam"

# IAM
iam_users:
  - "test_user1"
  - "test_user2"
iam_group_name: "test_group"
iam_group_membership_name: "iam_group_membership_name"
pgp_key: "mI0EYHP/agEEAOWB0HKjxjYiBXJyXDYykjGvtGc1dXMX0ThxFlAbSj/jNLyIABn/wtwm5H84zPIXS5Jp4vTudhnYqwr7Gz6eJGSdj83m+W6LfvFfbWhZR/t4yZEmh7PYiosAlKPBlQcQRuYPBXYfkq+Eypic4abvVPZ6f2ysr97GNbv9LtIWHprhABEBAAG0BXZhbGlziLkEEwECACMFAmBz/2oCGwMHCwkIBwMCAQYVCAIJCgsEFgIDAQIeAQIXgAAKCRAUCCy9bJ3PHrmkA/0X898RbjQlom9sYF9acSLtfHcjztZzN0M8RM+wIoSjcmJ6Lt8yGM9Hg7Ch/VVQh04irMf8DUhntUgS50OgqIFGd9ctumuUHcRVd6FRC+M+/zJR1B1lHMLDfUJZCiYkV7Cgtu2AdiW8iUM3kSLnceeMrBYVZ9d79AjtehScAeFCxLiNBGBz/2oBBACicp7VNJNKDHWHoiF0g8DuuLdTzBfTIKicXokK4BVqKK1UML0pQyZjrE18Hhyu5yzkNiUJ2QgAdbAMzj+DV2SszZwiLLv4LwRy6q60Off6GTB5yII9DBtqOYnlgHbcgaVINE1mqRj9u2WV3NkH4fPaHkKXxyQw3LCgEcfKBmjIqwARAQABiJ8EGAECAAkFAmBz/2oCGwwACgkQFAgsvWydzx7JZgQAwGwQadcO7sHF0AUCDgjOjkgBCQCMAnXK2LN4D6HCgaHTuDPTqxnFnz6jq/PH4gSqW/oABUJVzrx+j/my9Yo7N382AHm33trm/aMR7J3FpX/wPq6Ciff2LlWJWagetiQGY0rMFnpic7FumC3bFAKDZuqIv7jVobAnhIgRiM1krnA="